import { Item, Flow } from '@/store/inventorySlice';

export const dummyStock: Item[] = [
  // Tools
  {
    code: 'HW001',
    name: 'Screwdriver Set - 12 Pieces',
    category: 'Hand Tools',
    size: 'Standard',
    quantity: 45,
    price: 29.99,
  },
  {
    code: 'HW002',
    name: 'Claw Hammer',
    category: 'Hand Tools',
    size: '16 oz',
    quantity: 3,
    price: 19.99,
  },
  {
    code: 'HW003',
    name: 'Cordless Drill Machine',
    category: 'Power Tools',
    size: '20V, 500W',
    quantity: 15,
    price: 89.99,
  },
  {
    code: 'HW004',
    name: 'Steel Nails Box',
    category: 'Fasteners',
    size: '2 inch, 500pcs',
    quantity: 120,
    price: 12.99,
  },
  {
    code: 'HW005',
    name: 'Wood Screws Box',
    category: 'Fasteners',
    size: '1.5 inch, 300pcs',
    quantity: 2,
    price: 14.99,
  },
  {
    code: 'HW006',
    name: 'Paint Brush Set',
    category: 'Painting Supplies',
    size: 'Assorted 5pcs',
    quantity: 35,
    price: 24.99,
  },
  {
    code: 'HW007',
    name: 'Measuring Tape',
    category: 'Measuring Tools',
    size: '25ft / 7.5m',
    quantity: 28,
    price: 9.99,
  },
  {
    code: 'HW008',
    name: 'Safety Work Gloves',
    category: 'Safety Equipment',
    size: 'Large',
    quantity: 4,
    price: 7.99,
  },
  {
    code: 'HW009',
    name: 'LED Work Light',
    category: 'Lighting',
    size: '50W, Rechargeable',
    quantity: 18,
    price: 34.99,
  },
  {
    code: 'HW010',
    name: 'Wire Cutters',
    category: 'Hand Tools',
    size: '8 inch',
    quantity: 22,
    price: 16.99,
  },
  {
    code: 'HW011',
    name: 'Pliers Set - 3 Pieces',
    category: 'Hand Tools',
    size: 'Standard',
    quantity: 31,
    price: 27.99,
  },
  {
    code: 'HW012',
    name: 'Wrench Set - Metric',
    category: 'Hand Tools',
    size: '8-19mm, 12pcs',
    quantity: 1,
    price: 45.99,
  },
  {
    code: 'HW013',
    name: 'Circular Power Saw',
    category: 'Power Tools',
    size: '1200W, 7.25"',
    quantity: 8,
    price: 129.99,
  },
  {
    code: 'HW014',
    name: 'Sandpaper Assorted Pack',
    category: 'Abrasives',
    size: 'Grits 60-400, 50pcs',
    quantity: 67,
    price: 8.99,
  },
  {
    code: 'HW015',
    name: 'Heavy Duty Tool Belt',
    category: 'Storage & Organization',
    size: 'Adjustable',
    quantity: 14,
    price: 32.99,
  },
  {
    code: 'HW016',
    name: 'Allen Key Set - Hex Keys',
    category: 'Hand Tools',
    size: '1.5-10mm, 9pcs',
    quantity: 42,
    price: 11.99,
  },
  {
    code: 'HW017',
    name: 'Spirit Level',
    category: 'Measuring Tools',
    size: '24 inch',
    quantity: 19,
    price: 18.99,
  },
  {
    code: 'HW018',
    name: 'Angle Grinder',
    category: 'Power Tools',
    size: '750W, 4.5"',
    quantity: 11,
    price: 79.99,
  },
  {
    code: 'HW019',
    name: 'Safety Goggles',
    category: 'Safety Equipment',
    size: 'Anti-fog, Clear',
    quantity: 56,
    price: 5.99,
  },
  {
    code: 'HW020',
    name: 'Utility Knife Set',
    category: 'Cutting Tools',
    size: 'Retractable, 3pcs',
    quantity: 33,
    price: 13.99,
  },
  {
    code: 'HW021',
    name: 'Extension Cord',
    category: 'Electrical',
    size: '50ft, 14AWG',
    quantity: 24,
    price: 26.99,
  },
  {
    code: 'HW022',
    name: 'Staple Gun',
    category: 'Fastening Tools',
    size: 'Heavy Duty',
    quantity: 17,
    price: 22.99,
  },
  {
    code: 'HW023',
    name: 'Bolt Assortment Kit',
    category: 'Fasteners',
    size: 'M6-M12, 300pcs',
    quantity: 89,
    price: 19.99,
  },
  {
    code: 'HW024',
    name: 'PVC Pipe Cutter',
    category: 'Plumbing Tools',
    size: 'Up to 1.5"',
    quantity: 13,
    price: 15.99,
  },
  {
    code: 'HW025',
    name: 'Stud Finder',
    category: 'Detection Tools',
    size: 'Electronic LCD',
    quantity: 9,
    price: 24.99,
  },
];

export const dummyFlow: Flow[] = [
  {
    _id: 'flow001',
    date: '2024-12-16T09:30:00Z',
    code: 'HW001',
    name: 'Screwdriver Set - 12 Pieces',
    action: 'IN',
    qty: 25,
    note: 'New stock arrival from supplier',
  },
  {
    _id: 'flow002',
    date: '2024-12-16T10:15:00Z',
    code: 'HW003',
    name: 'Cordless Drill Machine',
    action: 'OUT',
    qty: 3,
    note: 'Customer order #1234',
  },
  {
    _id: 'flow003',
    date: '2024-12-16T11:00:00Z',
    code: 'HW019',
    name: 'Safety Goggles',
    action: 'IN',
    qty: 50,
    note: 'Restocking safety equipment',
  },
  {
    _id: 'flow004',
    date: '2024-12-15T16:45:00Z',
    code: 'HW002',
    name: 'Claw Hammer',
    action: 'OUT',
    qty: 7,
    note: 'Retail sale',
  },
  {
    _id: 'flow005',
    date: '2024-12-15T14:20:00Z',
    code: 'HW005',
    name: 'Wood Screws Box',
    action: 'OUT',
    qty: 8,
    note: 'Contractor bulk order',
  },
  {
    _id: 'flow006',
    date: '2024-12-15T13:30:00Z',
    code: 'HW006',
    name: 'Paint Brush Set',
    action: 'IN',
    qty: 15,
    note: 'Monthly restocking',
  },
  {
    _id: 'flow007',
    date: '2024-12-15T12:10:00Z',
    code: 'HW008',
    name: 'Safety Work Gloves',
    action: 'OUT',
    qty: 6,
    note: 'Industrial bulk order',
  },
  {
    _id: 'flow008',
    date: '2024-12-15T10:00:00Z',
    code: 'HW009',
    name: 'LED Work Light',
    action: 'IN',
    qty: 12,
    note: 'New product line addition',
  },
  {
    _id: 'flow009',
    date: '2024-12-14T16:30:00Z',
    code: 'HW012',
    name: 'Wrench Set - Metric',
    action: 'OUT',
    qty: 4,
    note: 'Auto mechanic shop order',
  },
  {
    _id: 'flow010',
    date: '2024-12-14T15:00:00Z',
    code: 'HW013',
    name: 'Circular Power Saw',
    action: 'IN',
    qty: 5,
    note: 'Warranty replacement stock',
  },
  {
    _id: 'flow011',
    date: '2024-12-14T11:20:00Z',
    code: 'HW021',
    name: 'Extension Cord',
    action: 'IN',
    qty: 20,
    note: 'Seasonal stock increase',
  },
  {
    _id: 'flow012',
    date: '2024-12-14T09:45:00Z',
    code: 'HW016',
    name: 'Allen Key Set - Hex Keys',
    action: 'OUT',
    qty: 8,
    note: 'Bike shop order',
  },
  {
    _id: 'flow013',
    date: '2024-12-13T16:00:00Z',
    code: 'HW023',
    name: 'Bolt Assortment Kit',
    action: 'IN',
    qty: 50,
    note: 'Bulk purchase from distributor',
  },
  {
    _id: 'flow014',
    date: '2024-12-13T14:30:00Z',
    code: 'HW018',
    name: 'Angle Grinder',
    action: 'OUT',
    qty: 2,
    note: 'Construction company order',
  },
  {
    _id: 'flow015',
    date: '2024-12-13T10:15:00Z',
    code: 'HW004',
    name: 'Steel Nails Box',
    action: 'IN',
    qty: 100,
    note: 'Regular supplier shipment',
  },
  {
    _id: 'flow016',
    date: '2024-12-12T15:45:00Z',
    code: 'HW020',
    name: 'Utility Knife Set',
    action: 'OUT',
    qty: 5,
    note: 'Warehouse fulfillment order',
  },
  {
    _id: 'flow017',
    date: '2024-12-12T13:00:00Z',
    code: 'HW017',
    name: 'Spirit Level',
    action: 'IN',
    qty: 10,
    note: 'New stock from manufacturer',
  },
  {
    _id: 'flow018',
    date: '2024-12-12T10:30:00Z',
    code: 'HW014',
    name: 'Sandpaper Assorted Pack',
    action: 'OUT',
    qty: 15,
    note: 'Woodworking shop order',
  },
  {
    _id: 'flow019',
    date: '2024-12-11T16:20:00Z',
    code: 'HW025',
    name: 'Stud Finder',
    action: 'IN',
    qty: 8,
    note: 'Tech equipment restock',
  },
  {
    _id: 'flow020',
    date: '2024-12-11T11:00:00Z',
    code: 'HW022',
    name: 'Staple Gun',
    action: 'OUT',
    qty: 3,
    note: 'Upholstery shop purchase',
  },
];
