import { Item, Flow } from '@/store/inventorySlice';

export const dummyStock: Item[] = [
  {
    code: 'HW001',
    name: 'Screwdriver Set',
    category: 'Tools',
    size: 'Standard',
    quantity: 45,
    price: 29.99,
  },
  {
    code: 'HW002',
    name: 'Hammer',
    category: 'Tools',
    size: 'Large',
    quantity: 3,
    price: 19.99,
  },
  {
    code: 'HW003',
    name: 'Drill Machine',
    category: 'Power Tools',
    size: '500W',
    quantity: 15,
    price: 89.99,
  },
  {
    code: 'HW004',
    name: 'Nails Box',
    category: 'Fasteners',
    size: '2 inch',
    quantity: 120,
    price: 12.99,
  },
  {
    code: 'HW005',
    name: 'Screws Box',
    category: 'Fasteners',
    size: '1.5 inch',
    quantity: 2,
    price: 14.99,
  },
  {
    code: 'HW006',
    name: 'Paint Brush Set',
    category: 'Painting',
    size: 'Assorted',
    quantity: 35,
    price: 24.99,
  },
  {
    code: 'HW007',
    name: 'Measuring Tape',
    category: 'Measuring',
    size: '25ft',
    quantity: 28,
    price: 9.99,
  },
  {
    code: 'HW008',
    name: 'Safety Gloves',
    category: 'Safety Equipment',
    size: 'Large',
    quantity: 4,
    price: 7.99,
  },
  {
    code: 'HW009',
    name: 'LED Work Light',
    category: 'Lighting',
    size: '50W',
    quantity: 18,
    price: 34.99,
  },
  {
    code: 'HW010',
    name: 'Wire Cutters',
    category: 'Tools',
    size: '8 inch',
    quantity: 22,
    price: 16.99,
  },
  {
    code: 'HW011',
    name: 'Pliers Set',
    category: 'Tools',
    size: 'Standard',
    quantity: 31,
    price: 27.99,
  },
  {
    code: 'HW012',
    name: 'Wrench Set',
    category: 'Tools',
    size: 'Metric',
    quantity: 1,
    price: 45.99,
  },
  {
    code: 'HW013',
    name: 'Power Saw',
    category: 'Power Tools',
    size: '1200W',
    quantity: 8,
    price: 129.99,
  },
  {
    code: 'HW014',
    name: 'Sandpaper Pack',
    category: 'Abrasives',
    size: 'Assorted',
    quantity: 67,
    price: 8.99,
  },
  {
    code: 'HW015',
    name: 'Tool Belt',
    category: 'Storage',
    size: 'Adjustable',
    quantity: 14,
    price: 32.99,
  },
];

export const dummyFlow: Flow[] = [
  {
    _id: 'flow001',
    date: '2024-12-10T10:30:00Z',
    code: 'HW001',
    name: 'Screwdriver Set',
    action: 'IN',
    qty: 20,
    note: 'New stock arrival',
  },
  {
    _id: 'flow002',
    date: '2024-12-11T14:15:00Z',
    code: 'HW003',
    name: 'Drill Machine',
    action: 'OUT',
    qty: 5,
    note: 'Customer order #1234',
  },
  {
    _id: 'flow003',
    date: '2024-12-12T09:00:00Z',
    code: 'HW004',
    name: 'Nails Box',
    action: 'IN',
    qty: 50,
    note: 'Supplier shipment',
  },
  {
    _id: 'flow004',
    date: '2024-12-12T16:45:00Z',
    code: 'HW002',
    name: 'Hammer',
    action: 'OUT',
    qty: 7,
    note: 'Retail sale',
  },
  {
    _id: 'flow005',
    date: '2024-12-13T11:20:00Z',
    code: 'HW005',
    name: 'Screws Box',
    action: 'OUT',
    qty: 8,
    note: 'Contractor order',
  },
  {
    _id: 'flow006',
    date: '2024-12-13T15:30:00Z',
    code: 'HW006',
    name: 'Paint Brush Set',
    action: 'IN',
    qty: 15,
    note: 'Restocking',
  },
  {
    _id: 'flow007',
    date: '2024-12-14T10:10:00Z',
    code: 'HW008',
    name: 'Safety Gloves',
    action: 'OUT',
    qty: 6,
    note: 'Bulk order',
  },
  {
    _id: 'flow008',
    date: '2024-12-14T13:00:00Z',
    code: 'HW009',
    name: 'LED Work Light',
    action: 'IN',
    qty: 10,
    note: 'New product line',
  },
  {
    _id: 'flow009',
    date: '2024-12-15T08:30:00Z',
    code: 'HW012',
    name: 'Wrench Set',
    action: 'OUT',
    qty: 4,
    note: 'Mechanic shop order',
  },
  {
    _id: 'flow010',
    date: '2024-12-15T11:00:00Z',
    code: 'HW013',
    name: 'Power Saw',
    action: 'IN',
    qty: 5,
    note: 'Warranty replacement',
  },
];